<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>StarWars.AzureFunctions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="RepoDb\**" />
    <EmbeddedResource Remove="RepoDb\**" />
    <None Remove="RepoDb\**" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Link="README.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Functions.Worker.HttpResponseDataJsonMiddleware" Version="1.2.0" />
    <PackageReference Include="Functions.Worker.HttpResponseDataCompression" Version="1.2.0" />
    <PackageReference Include="Functions.Worker.ILoggerSupport" Version="1.2.0" />
    <PackageReference Include="HotChocolate.AzureFunctions.IsolatedProcess" Version="16.6.0" />
    <PackageReference Include="HotChocolate.Types.Analyzers" Version="16.6.0" />
    <PackageReference Include="HotChocolate.PersistedQueries.FileSystem" Version="13.9.16" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
    <PackageReference Include="RepoDb.SqlServer" Version="1.13.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GraphQL.RepoDB.SqlServer\GraphQL.RepoDb.SqlServer.csproj" />
    <ProjectReference Include="..\GraphQL.ResolverProcessingExtensions\GraphQL.ResolverProcessingExtensions.csproj" />
    <ProjectReference Include="..\RepoDbExtensions.SqlServer.PagingOperations\RepoDbExtensions.SqlServer.PagingOperations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    <None Update="PersistedQueries\AllCharactersWithFriendsPaginated-v1.graphql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
