<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="16.6.0" />
    <PackageReference Include="HotChocolate.Data" Version="16.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="6.0.20" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphQL.RepoDb.SqlServer\GraphQL.RepoDb.SqlServer.csproj" />
    <ProjectReference Include="..\GraphQL.ResolverProcessingExtensions\GraphQL.ResolverProcessingExtensions.csproj" />
  </ItemGroup>

</Project>
